// Centralized product data from all produce categories
// Slugs match the arrowHref paths (without /produce/ prefix)
export const allProducts = [
  // Leafy Greens
  {
    image: "/OurProduce/LeafyGreens/speciality Chef's Mix.jpg",
    alt: "Specialty Chef's Mix",
    category: "LEAFY GREENS",
    productName: "Specialty Chef's Mix",
    description: "A wholesome mix of leafy greens combining crunch, color, and refreshing aroma.",
    slug: "specialty-chefs-mix",
  },
  {
    image: "/OurProduce/LeafyGreens/Romaine.jpg",
    alt: "Romaine Lettuce",
    category: "LEAFY GREENS",
    productName: "Romaine Lettuce",
    description: "Crisp, sturdy leaves with a mild, refreshing flavor.",
    slug: "romaine-lettuce",
  },
  {
    image: "/OurProduce/LeafyGreens/Kale.jpg",
    alt: "Kale",
    category: "LEAFY GREENS",
    productName: "Kale",
    description: "Nutrient-dense leafy green with a hearty, earthy taste.",
    slug: "kale",
  },
  {
    image: "/OurProduce/LeafyGreens/Red Leaf Lettuce.jpg",
    alt: "Red Leaf Lettuce",
    category: "LEAFY GREENS",
    productName: "Red Leaf Lettuce",
    description: "Tender leaves with a slightly sweet, delicate flavor.",
    slug: "red-leaf-lettuce",
  },
  {
    image: "/OurProduce/LeafyGreens/Green Leaf Lettuce.jpg",
    alt: "Green Leaf Lettuce",
    category: "LEAFY GREENS",
    productName: "Green Leaf Lettuce",
    description: "Soft, leafy texture with a mild and fresh taste.",
    slug: "green-leaf-lettuce",
  },
  {
    image: "/OurProduce/LeafyGreens/Basil.jpg",
    alt: "Basil",
    category: "LEAFY GREENS",
    productName: "Basil",
    description: "Aromatic herb with a sweet, peppery fragrance and vibrant flavor.",
    slug: "basil",
  },
  {
    image: "/OurProduce/LeafyGreens/Butter Head Lettuce.jpg",
    alt: "Butter Head Lettuce",
    category: "LEAFY GREENS",
    productName: "Butter Head Lettuce",
    description: "A soft, tender leafy green with a mild, buttery flavor perfect for fresh salads and wraps.",
    slug: "butter-head-lettuce",
  },
  {
    image: "/OurProduce/LeafyGreens/Bok.jpg",
    alt: "Bok Choy",
    category: "LEAFY GREENS",
    productName: "Bok Choy",
    description: "A crisp, nutritious leafy green with juicy stalks and tender leaves, commonly used in stir-fries and soups.",
    slug: "bok-choy",
  },
  // Baby Greens
  {
    image: "/OurProduce/BabyGreens/Speciality Chef's Mix.jpg",
    alt: "Specialty Chef's Mix",
    category: "BABY GREENS",
    productName: "Specialty Chef's Mix",
    description: "A wholesome mix combining earthy spinach, hearty kale, and zesty sorrel vein leaf.",
    slug: "specialty-chefs-mix",
  },
  {
    image: "/OurProduce/BabyGreens/Spinach.jpg",
    alt: "Spinach",
    category: "BABY GREENS",
    productName: "Spinach",
    description: "Soft, nutrient-rich leaves with a mild, earthy flavor.",
    slug: "spinach",
  },
  {
    image: "/OurProduce/BabyGreens/Baby Kale.jpg",
    alt: "Baby Kale",
    category: "BABY GREENS",
    productName: "Baby Kale",
    description: "Hearty, dark green leaves packed with bold, earthy taste.",
    slug: "baby-kale",
  },
  {
    image: "/OurProduce/BabyGreens/Sorrel.jpg",
    alt: "Sorrel Vein Leaf",
    category: "BABY GREENS",
    productName: "Sorrel Vein Leaf",
    description: "Bright, tangy leaves with a refreshing, lemony bite.",
    slug: "sorrel-vein-leaf",
  },
  // MicroGreens
  {
    image: "/OurProduce/MicroGreens/Speciality Chef's Mix.jpg",
    alt: "Specialty Chef's Mix",
    category: "MICROGREENS",
    productName: "Specialty Chef's Mix",
    description: "A fresh, colorful mix of nutrient-packed microgreens with mild to zesty flavors.",
    slug: "microgreens-specialty-chefs-mix",
  },
  {
    image: "/OurProduce/MicroGreens/Red Amaranthus.jpg",
    alt: "Red Amaranthus",
    category: "MICROGREENS",
    productName: "Red Amaranthus",
    description: "Tender, vibrant red leaves with a mild, earthy flavor.",
    slug: "microgreens-red-amaranthus",
  },
  {
    image: "/OurProduce/MicroGreens/Mizuna.jpg",
    alt: "Mizuna",
    category: "MICROGREENS",
    productName: "Mizuna",
    description: "Delicate, feathery greens with a light peppery taste.",
    slug: "microgreens-mizuna",
  },
  {
    image: "/OurProduce/MicroGreens/Basil.jpg",
    alt: "Basil",
    category: "MICROGREENS",
    productName: "Basil",
    description: "Aromatic leaves with a sweet, peppery fragrance and bold flavor.",
    slug: "microgreens-basil",
  },
  {
    image: "/OurProduce/MicroGreens/Kale.jpg",
    alt: "Kale",
    category: "MICROGREENS",
    productName: "Kale",
    description: "Hearty, nutrient-dense leaves with a rich, earthy taste.",
    slug: "microgreens-kale",
  },
  {
    image: "/OurProduce/MicroGreens/Arugula.jpg",
    alt: "Arugula",
    category: "MICROGREENS",
    productName: "Arugula",
    description: "Peppery, zesty greens with a sharp, fresh bite.",
    slug: "microgreens-arugula",
  },
  {
    image: "/OurProduce/MicroGreens/Red Cabbage.jpg",
    alt: "Red Cabbage",
    category: "MICROGREENS",
    productName: "Red Cabbage",
    description: "Crisp purple leaves with a slightly sweet, crunchy flavor.",
    slug: "microgreens-red-cabbage",
  },
  // Specialty Herbs
  {
    image: "/OurProduce/SpecialityHerbs/Chef'sMix.jpg",
    alt: "Specialty Chef's Mix",
    category: "SPECIALTY HERBS",
    productName: "Specialty Chef's Mix",
    description: "Aromatic leafy and specialty herbs with fresh, tangy, and fragrant flavors.",
    slug: "specialty-chefs-mix",
  },
  {
    image: "/OurProduce/SpecialityHerbs/The Basil.jpg",
    alt: "Thai Basil",
    category: "SPECIALTY HERBS",
    productName: "Thai Basil",
    description: "A fragrant specialty herb with a spicy, anise-like flavor, widely used in Southeast Asian cuisine.",
    slug: "thai-basil",
  },
  {
    image: "/OurProduce/SpecialityHerbs/Dill.jpg",
    alt: "Dill",
    category: "SPECIALTY HERBS",
    productName: "Dill",
    description: "A delicate specialty herb with feathery leaves and a fresh, slightly tangy flavor, ideal for seafood and dressings.",
    slug: "dill",
  },
  {
    image: "/OurProduce/SpecialityHerbs/Lemon Balm.jpg",
    alt: "Lemon Balm",
    category: "SPECIALTY HERBS",
    productName: "Lemon Balm",
    description: "A refreshing specialty herb with a gentle lemon aroma, commonly used in teas and wellness blends.",
    slug: "lemon-balm",
  },
  {
    image: "/OurProduce/SpecialityHerbs/Sorrel.jpg",
    alt: "Sorrel",
    category: "SPECIALTY HERBS",
    productName: "Sorrel",
    description: "A vibrant specialty herb with tender leaves and a sharp, lemony taste, perfect for soups and sauces.",
    slug: "sorrel",
  },
  {
    image: "/OurProduce/SpecialityHerbs/itialian Basil.jpg",
    alt: "Italian Basil",
    category: "SPECIALTY HERBS",
    productName: "Italian Basil",
    description: "A classic specialty herb with sweet, aromatic leaves, essential in Italian and Mediterranean dishes.",
    slug: "italian-basil",
  },
  // Edible Flowers
  {
    image: "/OurProduce/EdibleFlowers/Speciality Chef's Mix.jpg",
    alt: "Specialty Chef's Mix",
    category: "EDIBLE FLOWERS",
    productName: "Specialty Chef's Mix",
    description: "Vibrant edible flowers with delicate, tangy, and slightly sweet flavors.",
    slug: "edible-flowers-specialty-chefs-mix",
  },
  {
    image: "/OurProduce/EdibleFlowers/Nasturtium.jpg",
    alt: "Nasturtium",
    category: "EDIBLE FLOWERS",
    productName: "Nasturtium",
    description: "Bright, peppery edible flowers with a spicy, tangy taste, perfect for salads and garnishes.",
    slug: "nasturtium",
  },
  {
    image: "/OurProduce/EdibleFlowers/Viola.jpg",
    alt: "Viola",
    category: "EDIBLE FLOWERS",
    productName: "Viola",
    description: "Delicate edible flowers with a mild, slightly sweet flavor, often used for garnishes and desserts.",
    slug: "viola",
  },
  {
    image: "/OurProduce/EdibleFlowers/Marigold Petals.jpg",
    alt: "Marigold Petals",
    category: "EDIBLE FLOWERS",
    productName: "Marigold Petals",
    description: "Colorful edible petals with a slightly citrusy, mildly bitter flavor, ideal for decoration and flavoring dishes.",
    slug: "marigold-petals",
  },
];

// Helper function to get product by slug
export function getProductBySlug(slug) {
  return allProducts.find(product => product.slug === slug);
}
